nginx:
  name: wp-proxy
  labels:
    id: c0927678
    app: wp-proxy-app
    env: dev
  image:
    repository: dhananjayakafle/custom-nginx
    tag: "latest"
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80